name: Airbyte CI

on:
  schedule:
    - cron: '0 */1 * * *'
  push:

jobs:
  logging:
    name: Log output
    runs-on: ubuntu-latest
    steps:
      - name: log output
        run: |
          echo "USER=$USER"
          whoami
          echo "HOME=$HOME"
          cd ~
          echo $(pwd)
